### PR TITLE
Change button styling to match Uiuapad's

### PR DESCRIPTION
**Pull request by roxwize**
This replaces the current default-styled buttons to match the ones shown on [uiua.org/pad](https://www.uiua.org/pad).

Some additional stuff you should know:
- `button`s now have the glyph itself wrapped in a `div` so that glyphs such as `⍉` display properly on a background.
- The logic for adding buttons has changed slightly. Rather than attaching a `mouseup` event to `#button-holder`, buttons are given a `click` event listener as they are creating that achieves the same purpose (minus the header that previously displayed the glyph's name; it isn't needed anymore).
- Current issue is that hovering over a button on the far right of the keypad cuts off the tooltip text, which will likely be a problem. A bodge would be to just give the button holder a right margin of 7em, but this wastes space. I don't recall a CSS feature that allows absolutely-positioned elements like the tooltip to change their position to remain within a container, but it can probably be done somehow, and I'm going to try to figure out how to go about that (hence the draft status).

Screenshot

### CODE REVIEW

**Comment by thehappycheese** [comment]
Hi @thekifake :) Thankyou for working on this.
I am really sorry I didn't see your PR until after I made a heap of changes today.
I'll take a look, I may have already made a few changes that improve the button style.

Regarding the tooltip, I am more inclined to stick with the current hover-status-bar at the top approach which eliminates the issues with tooltips overlapping things. Is there a reason you wanted to change the tooltip style?
I was worried that the existing status bar text might be hidden by some themes? In today's changes I manually set the font color and body background color to help ensure that themes don't make the text invisible.

I think you are right that wrapping the button contents in a div may help to fix the formatting, especially for the trans glyph.

**Comment by roxwize** [comment]
> Regarding the tooltip, I am more inclined to stick with the current hover-status-bar at the top approach which eliminates the issues with tooltips overlapping things. Is there a reason you wanted to change the tooltip style?

I changed it primarily to match what appeared on the Uiua website (for consistency, I suppose). In retrospect the original method of using a header might be the better option. Though, it might be worth trying to add the description of the glyph beneath it, sort of similiar to Uiuapad displaying a small info box when you hover over a glyph:

image

The one thing preventing me from implementing this easily, though, is the fact that these one line summaries of the functions aren't contained in a database, or anything. They're contained as comments in [the defs.rs file of the language itself](https://github.com/uiua-lang/uiua/blob/main/src/primitive/defs.rs). This works in the context of the website because I assume it's a feature of Rust similar to JSDoc, except you can extract the documentation as a string (I'm not familiar with Rust so I could be wrong). However trying to get this information from the file *outside* of Rust, without making changes to the `defs.rs` file itself, would involve something like a regular expression which, while it can be written, will probably be relatively slow and I'm not sure it would mesh well with the pre-existing method you have for getting glyph icons and names. It might be worth a shot regardless.

Despite the fact that you've already made the thematic changes to the buttons, I'm still going to keep this open as a draft in the hopes that I can maybe implement what I've just described. I will say that, in the current version, the keypad does seem a bit zoomed in, and justifying the individual buttons to the center would likely look a lot better. The grid misalignment it will likely introduce could probably be fixed by just making the backgrounds of the buttons transparent until hover, like in my implementation (if that makes any sense).

**Comment by thehappycheese** [comment]
> for consistency

Ah thats fair enough. I guess it is best to make it an easy switch from the web version.
I am not sure if it is implemented yet, but I thought of this article from google about tooltip anchoring; https://developer.chrome.com/blog/whats-new-css-ui-2023/#anchor-positioning

Even so, in VS code the keypad will generally have quite a lot of extra space, especially in tall-skinny aspect ratios. Plenty of room to put the tooltip as a status bar. Maybe in short-wide aspect ratios it could switch to a tooltip strategy?

> the defs.rs file

Ah well done I made a few attempts to find it but gave up :)
I certainly could parse the source... but I am reluctant to try since it is unstable. I tried once on the discord to ask if there is a JSON definition that could be queried but no response from the language author yet.

If it is in rust as a macro, perhaps more rust macro wizardry could be use to make an endpoint that can be queried...

>  does seem a bit zoomed in

Agreed. I struggled with the media queries a bit to fix it... but without knowing the aspect ratio (skinny tall, or wide short, or square) it is hard to optimize the styles for all situations and sizes.
I would welcome any improvements to the current media query mess. Possibly the border-radius and grid/flex gap needs to be decoupled from the font-size to get a more consistent appearance... dunno.

> justifying the individual buttons to the center would likely look a lot better. The grid misalignment it will likely introduce could probably be fixed by just making the backgrounds of the buttons transparent until hover, like in my implementation (if that makes any sense).

I think I did end up with everything centered? Anyway I am sure it could be improved further.

I will try just stick to just updating glyphs for a while.
Thanks again and hopefully you get a chance to update your PR :)

**Comment by roxwize** [comment]
Closing this since it's been obsoleted and I don't plan on making future changes to it.

**Pull request closed without merging**
